### ISSUE TITLE
Missing zone migration

### ISSUE THREAD

**Issue by hatsat32** [auroraresearchlab/netbox-dns#102]
After new PRs merged I see there is a missing migration.

```
$ python3 manage.py makemigrations
Migrations for 'netbox_dns':
  /home/ausec/Dev/netbox-dns/netbox_dns/migrations/0007_alter_zone_soa_serial_auto.py
    - Alter field soa_serial_auto on zone
```

Here is the content of `0007_alter_zone_soa_serial_auto.py`

```python
# Generated by Django 3.2.9 on 2021-12-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dns', '0006_zone_soa_serial_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='soa_serial_auto',
            field=models.BooleanField(default=True),
        ),
    ]
```

Investigating this issue I see that it might be related to PR #74.

Here are the added lines (135 - 139) to `models.py` in this PR

```python
soa_serial_auto = models.BooleanField(
    verbose_name="Generate SOA Serial",
    help_text="Automatically generate the SOA Serial field",
    default=True,
)
```

Here is the result migration. Lines 14 - 18.

```
    ....
        operations = [
        migrations.AddField(
            model_name="zone",
            name="soa_serial_auto",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ....
```
default "true" value not reflected in the migration file.

If I am missing something, please let me know

**Comment by peteeckel** [comment]
You are correct - this migration is missing indeed. But the error is not in the migration, but in the model - the default for soa_serial_auto should be "True" only for new zones as setting it for existing zones would lose data: When the field is set to "true", all existing serial numbers will be overwritten, which is definitely not intended in a migration.

If there are existing zones with a fixed SOA and the new feature is added, the existing zones should stay as they are until they are switched to soa_serial_auto. I'll have a look at it later this week.
