### ISSUE TITLE
TableControls Error on Netbox v3.1.2

### ISSUE THREAD

**Issue by martydingo** [auroraresearchlab/netbox-dns#112]
Hiya there,

I've had some issues accessing all web pages in Netbox, due to an error regarding `inc/table_controls.html` not existing.

I can successfully load pages such as 'zones' and 'nameservers' when copying  to `inc/table_controls.html` via

`cd /opt/netbox/netbox/templates/inc; cp table_controls_htmx.html table_controls.html`

So it seems this plugin should reference `table_controls_htmx.html`, rather then `table_controls.html`

**Comment by hatsat32** [comment]
Hi @martydingo.

Please see PR #113

This should fix the issue.

**Comment by martydingo** [comment]
Many thanks @hatsat32 !
