### ISSUE TITLE
Quick search does not work

### ISSUE THREAD

**Issue by fabricat** [auroraresearchlab/netbox-dns#142]
Trying to use the "Quick search" box in the Records list, but nothing happens.
Actually, I don't see any REST request sent, nor Javascript errors in the browser console (Chrome).

**Comment by peteeckel** [comment]
Could you please post the exact versions you're currently using, including the browser type and version?

It had exactly the same issue but it "magically" went away at some point (I'm constantly testing and upgrading because of the work on the new version that will be compatible with NetBox 3.2), so I can't figure out what's the reason. It would help if I could find a way to reproduce it reliably.

**Comment by fabricat** [comment]
I have Netbox v3.1.9 (deployed with Docker) and Netbox DNS v0.8.0.
Google Chrome version 99.0.4844.51 64-bit, but the same happens with Firefox 98.0.
Thanks.

**Comment by peteeckel** [comment]
Thanks! I'm able to reproduce it now.

At one customer's site I'm currently running NetBox DNS version 0.8 with Netbox 3.1.1, and the problem does not show up there, which is a bit odd.

However, it could be that the new NetBox version 3.2 comes out before this can be fixed, and in that case it will likely be fixed anyway - I can't reproduce it with the current NetBox 3.2 beta and the "netbox32-changes" branch, although nothing that should be relevant to Quick Search has changed in NetBox DNS's code.

**Comment by fabricat** [comment]
I have now deployed Netbox 3.1.10 with Netbox-DNS 9.1: the same issue happens 😢

**Comment by hatsat32** [comment]
Hi. I think I found the issue. In `record_list.html` line 103 netbox tries to use `inc/table.html` but netbox 3.1.10 does not work that way. Maybe we can add another version check in there. Something like this:

```html
{# Object table #}
<div class="card">
  {% if '3.1.2'|check_version %}
    <div class="card-body">
      <div class="table-responsive">
        {% render_table table 'inc/table.html' %}
      </div>
    </div>
  {% else %}
    <div class="card-body" id="object_list">
      {% include 'htmx/table.html' %}
    </div>
  {% endif %}
</div>
```

same issue exist in `object_list.html`

**Comment by hatsat32** [comment]
PR #159 fixes most of the issue but , because of old limited plugin support, I could not find any proper fix for zone detail lists.

**Comment by peteeckel** [comment]
I'm afraid we won't come any closer to a working version on 3.1.x. Hopefully 3.2 will be finished soon.

**Comment by hatsat32** [comment]
Hi @fabricat . Can you please check version 0.9.2 and give us some feedback please?

**Comment by fabricat** [comment]
Hi @hatsat32 
I have upgraded the plugin and the quick search now works fine 👍 
(I am also looking forward to try the Netbox 3.2 as well.)

Thank you so much for the support.
