### ISSUE TITLE
TemplateNotFoundException under netbox v3.1.10

### ISSUE THREAD

**Issue by matejv** [auroraresearchlab/netbox-dns#155]
After upgrading to netbox v3.1.10 the netbox-dns plugin table views stopped working with exception: `TemplateNotFoundException inc/table_controls.html`. After I rolled back to netbox v3.1.9 netbox-dns works again.

I'm guessing this is the same issue as mentioned in #154 (comparing `VERSION`) and will be fixed in next netbox-dns plugin release.

Just wanted to put a note here in case anyone else stumbles onto this error.

**Comment by matejv** [comment]
Thank you.

Updated to netbox 3.1.10 and netbox-dns 0.9.0 and the "top-level" table views now work.

But I get an error on the following views:

- /plugins/netbox-dns/zones/1/records/
- /plugins/netbox-dns/zones/1/managedrecords/

Error is:

```
<class 'django.template.exceptions.TemplateSyntaxError'>

Invalid filter: 'check_version'

Python version: 3.9.5
NetBox version: 3.1.10
```

**Comment by hatsat32** [comment]
Sorry. PR #157 should fix the issue.

**Comment by matejv** [comment]
Installed 0.9.1, all views seem to work fine.

Thank you very much!
