### ISSUE TITLE
Prepare for NetBox 3.2 final

### ISSUE THREAD

**Issue by peteeckel** [auroraresearchlab/netbox-dns#161]
Yesterday NetBox 3.2 was released.

There are some little issues with the interoperability, and some final adjustments to to to NetBox DNS in order to be fully compatible with this release:

* Migration fails with an error message because CHOICES is a tuple, not a list
* Filtering and Quick search in Zone Record and Managed Record lists does not work (and probably won't without major effort)
* The `zone_edit.html` template is no longer necessary as it can be replaced by fieldsets

**Comment by DonMusto** [comment]
Yeahhh, this fails for me due to the above. :(

**Comment by peteeckel** [comment]
I'm not sure whether it's a bug in NetBox or intended - NetBox checks the CHOICES setting with `is_list`, so it fails when it's actually a tuple (which was working in pre-release 3.2, so it caught me cold).

**Comment by peteeckel** [comment]
> I'm not sure whether it's a bug in NetBox or intended - NetBox checks the CHOICES setting with `is_list`, so it fails when it's actually a tuple (which was working in pre-release 3.2, so it caught me cold).

Not a bug at all.

When using a ChoiceSet there is the option of configuring additional choices in configurition. To do that, a key needs to be defined in the ChoiceSet (defining the name of the configuration option for the ChoiceSet), and the CHOICES value needs to be mutable - which is what NetBox checks. This was introduced in NetBox commit 830b56ac9 on April 5th.
