### ISSUE TITLE
Description and enable/disable fields for records

### ISSUE THREAD

**Issue by mikat-gh** [auroraresearchlab/netbox-dns#206]
Hi,

I have been evaluating using netbox-dns for DNS management and liking it so far. Two suggestions for additional fields:

- A checkbox or status for disabling individual records from actual zone export without deleting. We often keep records disabled first and only after a while delete them. This would probably need to be OR'd with the zone status for current Active field. 

- Freeform description / comment for records (maybe zones also) would be nice, similar to IP addresses.

We can add these as custom fields, but I believe they would be useful to have by default.

**Comment by peteeckel** [comment]
Hi @mikat-gh! Agreed, it would definitely make sense to put a status field on records (no big deal), and actually the same is true for nameservers (views not so much, though it will probably not hurt to have it and some users might find it useful for their purposes).

Thinking it through, it might make sense to add a "Description" field to all object types, views, zones, nameservers and records, not only records.

Noted, will do it as soon as I find the time. Great suggestion, thanks!
