### ISSUE TITLE
Custom fields not shown on record details

### ISSUE THREAD

**Issue by fabricat** [auroraresearchlab/netbox-dns#208]
I have configured a custom field on Netbox-DNS record objects: it works ok when editing and listing/filtering records... but the custom field is **not shown on the detail view** of single record!

FYI I have created such a custom field in order to associate records with internal ticket requests... but a generic "Description" field as requested in #206 would be useful as well 😄 

Regards.

**Comment by peteeckel** [comment]
Records have a very specific custom template, and it may well be that I missed custom fields when I created it. I will look at it as soon as possible. 

As for descriptions, PR #207 already added them (not merged to main yet, but it should work fine). Status is still in the queue, though.

**Comment by peteeckel** [comment]
Should be fine with PR #209 ... just a very trivial change.

**Comment by fabricat** [comment]
Thanks. Do you know when is the fix expected to be merged and released?
