### ISSUE TITLE
associated zones not visible on REST API nameservers endpoint

### ISSUE THREAD

**Issue by LuPo** [auroraresearchlab/netbox-dns#230]
Description:

It is impossible to retrieve the related zones querying nameservers API, while the nested zone table in displayed in the Nameserver detail View. This makes me think that it has not been omitted due to performance concerns.
This search however is possible through the GraphQL with query like:
```
query{
  nameserver_list {
    name
    zones {
      name
    }
  }
}
```

How to implement:
add  NestedZoneSerializer as an attribute on NameServerSerializer

Database changes:
None as the relationship between zone and nameserver objects is already of type many-to-many

If you think it is worth implementation, I can try the PR

**Comment by peteeckel** [comment]
I think it makes perfect sense, so sure, go on! If you need any help just shout.

**Comment by LuPo** [comment]
I have opted for keeping the nested Zones serializer in readonly mode. It looks like we don't need to extend the tests.

**Comment by peteeckel** [comment]
Making serializers writable is sometimes a bit tricky, though manageable. ATM I don't see much point in the effort though so we should get along fine with a read-only variant. Creating zones on the fly with name servers is probably not a common use case, so you would want to limit it to existing zones anyway. As long as the tests pass it should be fine. 

Sometimes getting the tests from the upstream project to pass is really a pain, as they are not actually supported for plugins yet and neither very well-documented nor flexibly configurable ... I hope in a later NetBox version https://github.com/netbox-community/netbox-wg8333/issues/16 will be addressed, which should relieve that pain.

**Comment by LuPo** [comment]
I agree. The PR in its simplest form is waiting for the revision. Let me know if I omitted anything important.
