### ISSUE TITLE
Zone default TTL handling in records

### ISSUE THREAD

**Issue by mikat-gh** [auroraresearchlab/netbox-dns#234]
Hi,

Currently there is no way to create record that would follow zone default TTL. When creating new record from GUI, zone default gets set on new records if TTL is empty, but that is one time set, it doesn't follow changes to default TTL. Also via API ttl value is required, so to set the default you need to fetch it from the zone data yourself.

I think there should be possibility to create records without set TTL, that follow zone default. Allowing null value for record TTL would be simplest? Export scripts then just need to handle that case however they see fit.

**Comment by peteeckel** [comment]
Here we go ... it was actually a much smaller change than expected, most effort went into documenting the breaking changes :-)

**Comment by mikat-gh** [comment]
Thanks, that was fast! I'm running out of issues ;-)
