### ISSUE TITLE
Incorrect PTR generated from zone apex

### ISSUE THREAD

**Issue by mikat-gh** [auroraresearchlab/netbox-dns#246]
Hi,

If there is A/AAAA record at zone apex with PTR generation enabled the PTR value set is "@.\<zone\>." instead of "\<zone\>."

**Comment by peteeckel** [comment]
Hi @mikat-gh, thanks! Nice one :-)

**Comment by mikat-gh** [comment]
Confirmed, with #247 corrent PTR is generated. 

Thank you for the quick fix, again!

**Comment by peteeckel** [comment]
You're welcome! Thanks for the useful issue reports, that really helps to smooth out the wrinkles.
