### ISSUE TITLE
Tips and tricks regarding automating DNS update

### ISSUE THREAD

**Issue by deku-m** [auroraresearchlab/netbox-dns#254]
Hi,

I wonder if someone already has this implemented automating dns with this plugin so that it can populate also the dns server like infobox, ms dns servers etc. I saw a couple of solutions in issues like web hooks, octodns, dispython..? But i don't know how to.

Is someone that has this working, might be useful to write it as tips and tricks on the webpage?

**Comment by peteeckel** [comment]
Hi @deku-m, welcome to the small but vibrant NetBox DNS community :-)

That said, your question is, while probably interesting for many users, not an issue. An issue would relate to a feature request or a bug report. Your question would be much better placed in the "Discussions" section, where you'll probably get answers from several users with different scenarios. 

Would you mind closing it and moving the discussion to ... well, to "Discussions"?

That said - I know several users are actively provisioning their DNS servers with data from NetBox DNS. I, for once, do it, for me and a couple of customers. There are some resources already present (e.g. in the "examples" directory), and some discussions have been started around that as well (e.g. #182). 

However, for you it would probably be the best solution to open a discussion, describe your operational scenario and ask for suggestions or advice. There's a variety of users here, and probably somebody's use case will be similar enough to yours.
