### ISSUE TITLE
Having a record with a TTL value of 'None' can cause downstream problems

### ISSUE THREAD

**Issue by wolfspyre** [auroraresearchlab/netbox-dns#264]
in #242 there were hardcoded TTLs... 
 #243   "fixed" that by setting the value to None... 

The problem *I* am running into with this is that when I've created zonefiles from the records, I'll get records with a value of None for the TTL... coredns doesn't like that. 

Granted, this could certainly be addressed in the script I'm using to generate zonefiles.

A potentially less problematic way ( not saying a BETTER way ) would be to allow per (install?|view?|nameserver?|zone?) 'defaults' which populate the hierarchically inferior records... Such that the value is not None.
then perhaps have an enum field describing where that record's value was last divined from.   (LOCKED/explicit/zone/nameserver/view/install/random/magic 8 ball... etc.)

This would allow for inheritance logic to apply where appropriate, while still having the record be accurate regardless of where the value was set.... 

I can see a legitimate argument for either way, Having a null value in the record saves database space, and provides a simple logic path to assert inheritance should take precedent....  at the cost of an incomplete record.

having an extra field declaring each record's TTL's origin consumes more space, and likely more CPU overhead in maintenance, but the records are accurate, which has an upside from the standpoint of integrations as the record is accurate from the perspective of an external inquiry without needing to know how to interpret a null value for a field that should have a numerical value....

¯\_(ツ)_/¯

**Comment by peteeckel** [comment]
@wolfspyre: On second thought ... is your problem that you get a textual `None`, `none`, `null` or whatever as the TTL? That would indicate a problem with your script - I know because I had the same problem after implementing #235. 

For Jinja 2/Ansible, the solution is to use something like
```
{{ (_record.ttl|string if _record.ttl is not none else '').ljust(8) }} 
```
instead of
```
{{ (_record.ttl|string).ljust(8) }} 
```
in your template so the TTL is replaced by an empty string if the value is absent.

**Comment by wolfspyre** [comment]
@peteeckel 

Yeah  yer right... it's not required and netbox-dns isn't expected to maintain it...

I was thinking about this from the perspective of other things (like ansible) slurping a record from netbox  as the source of truth and barfing because missing expectations....
 
Wholly agree with you that it's more integration-implementation-specific nuance than pedantic correctness.
(feature not bug)


And thanks for pushing back on this... I don't believe my ideas are fantastic... I don't USUALLY think they're either terrible, but I do value the discussion around implementation points that may or may not be worth the squeeze.
 Admittedly,  git issues aren't REALLY the best medium for these kinds of conversations... but I was thinking that raising this issue might have the positive upside of  
> oh hey someone else ran into this too and....fixed it by.... 
 
and yes, I'd already fixed in my`^H^H`the script you so generously shared as a starting point.... pretty much the same as you did there except I used the numerical 3600... Yer way's prolly better ... but.... ¯\\\_(ツ)_/¯ 

regardless.... hope yer day's going awesomely! thanks again!

❤️🐺W

**Comment by peteeckel** [comment]
Hi @wolfspyre, thanks!

While GitHub issues are not the right place to discuss this kind of abstract and less-concise implementation ideas, I'd gladly point to discussions - if there were more participation (ha, ha) they'd be a good place to incubate ideas.

Glad my afterthought worked for you.
