### ISSUE TITLE
Couldn't install

### ISSUE THREAD

**Issue by mcules** [auroraresearchlab/netbox-dns#283]
I have netbox (v3.4.4) running in docker containers.
Tried to install the netbox-dns like other plugins too.

1. Added "netbox-dns" to plugin_requirements.txt
2. Added "netbox-dns" to Plugins array in configuration/configuration.py
3. docker-compose build --no-cache

Tried with console and pip install too.

pip install showed me that the requirements are installed.

But when the plugin is activated in configuration, i get that error and the container isn't starting:

`django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox-dns: Module not found. Check that the plugin module has been installed within the correct Python environment.`

How can i solve that?

**Comment by klenzel** [comment]
Instead of configuration/configuration.py try to add the plugin in configuration/plugins.py:
PLUGINS = [
        "netbox_dns",
]

**Comment by peteeckel** [comment]
> Instead of configuration/configuration.py try to add the plugin in configuration/plugins.py:
> 
> PLUGINS = [
> 
>         "netbox_dns",
> 
> ]

It's not so much a question of where to configure the plugin, it's the spelling: Not `netbox-dns`, but `netbox_dns` (note the underscore).

I think that is what made the install fail.

**Comment by mcules** [comment]
That underscore needs a "wasted time counter".
I actually just missed the underscore. I checked it several times with the pip install, but overlooked it with the config.
It's working now, thanks for your help.
