### ISSUE TITLE
Inhibit creation of incompatible record types in zones

### ISSUE THREAD

**Issue by peteeckel** [auroraresearchlab/netbox-dns#72]
Generally in a reverse zone there can't be any A/AAAA records and in a non-reverse zone there can't be any PTR records.

To improve the reliability of the system, creating records of the wrong type should be inhibited on the form and/or model level. Some other record types (e.g. MX) will also be affected by the same restrictions on PTR zones.

**Comment by JuergenKammer** [comment]
Generally? See RFC 1101 for corner cases: network masks may show up as A records in reverse zones if you want to make your subnetting visible, and PTR records in non-reverse zones if you track "network names" (wow!?). Though I am quite unsure if we'll find these usages nowadays in the wild. OTOH prohibiting it does not feel right (could i.e. be used for documentation in internal views).
Nevertheless, prohibiting (definitly) wrong entries is the right idea.

**Comment by peteeckel** [comment]
This issue is a bit too broad to be handled in one single change. Most of what it intends has been implemented by the record validation code in #181 and #175, and as @JuergenKammer pointed out some parts of this issue don't actually make as much sense as they seemed to.
