### ISSUE TITLE
Problem with pynetbox and the "netbox_dns" application label

### ISSUE THREAD

**Issue by peteeckel** [auroraresearchlab/netbox-dns#75]
Hi, 

we have a problem.

I was just trying to use the Ansible Netbox plugin to fetch data from netbox_dns.

Apart from some pretty strange bugs in the Ansible plugin itself (which are not part of this problem), it uses the pynetbox Python module to access Netbox. And here's where the trouble starts.

When pynetbox creates an endpoint object to access Netbox, it rewrites the application name so that underscores are converted to dashes in the URL. So, to access, for example, nameservers, it constructs the API URL as follows: `https://netbox.example.com/api/plugins/netbox-dns/nameservers/` which obviously will not work, as the real URL is `https://netbox.example.com/api/plugins/netbox_dns/nameservers/`.

This behaviour is hard-coded in `pynetbox/core/endpoint.py`:
```
    def __init__(self, api, app, name, model=None):
        self.return_obj = self._lookup_ret_obj(name, model)
        self.name = name.replace("_", "-")                                         <----
        self.api = api
        self.base_url = api.base_url
        self.token = api.token
        self.session_key = api.session_key
        self.url = "{base_url}/{app}/{endpoint}".format(
            base_url=self.base_url, app=app.name, endpoint=self.name,
        )
        self._choices = None
```

To really get rid of this it's probably necessary to change the URL schema so that it uses a dash instead of an underscore.

While not strictly forbidden, there are several recommendations around against using underscores in URLs (e.g. [here](https://developers.google.com/search/docs/advanced/guidelines/url-structure?hl=en&visit_id=637738725805263793-3338912307&rd=1), Caution: Google link), and this seems to be one of the occasions where it really bites.

**Comment by peteeckel** [comment]
Workaround for those using the Apache HTTP daemon:

```
    ProxyPreserveHost On
    ProxyPassMatch "/api/plugins/netbox-dns/(.*)$" "http://localhost:8001/api/plugins/netbox_dns/$1"
    ProxyPass / http://localhost:8001/
    ProxyPassReverse / http://localhost:8001/
```

The "ProxyPassMatch" rule rewrites the dash-formatted URLs back to URLs that netbox_dns can handle.

**Comment by hatsat32** [comment]
Thank for creating issue.

We have another optional solution. When we started this project I forgot adding `base_url = "netbox-dns"` configuration to `DNSConfig` in `netbox_dns/__init__.py`. It is my bad sorry :( With this change, we can solve this issue but we will have a few breaking changes.

Api endpoints will change `/api/plugins/netbox_dns/` to `/api/plugins/netbox-dns/`:

Old endpoints:

```
# GET /api/plugins/netbox_dns/

{
    "nameservers": "http://127.0.0.1:8000/api/plugins/netbox_dns/nameservers/",
    "records": "http://127.0.0.1:8000/api/plugins/netbox_dns/records/",
    "zones": "http://127.0.0.1:8000/api/plugins/netbox_dns/zones/"
}
```

New endpoints:

```
# GET /api/plugins/netbox-dns/

{
    "nameservers": "http://127.0.0.1:8000/api/plugins/netbox-dns/nameservers/",
    "records": "http://127.0.0.1:8000/api/plugins/netbox-dns/records/",
    "zones": "http://127.0.0.1:8000/api/plugins/netbox-dns/zones/"
}
```

Web UI endpoints will also change but it will not have much effect.

So what do you think?

**Comment by peteeckel** [comment]
Given the fact that we'll probably not going to convince the maintainers of pynetbox to change the logic on their end (and that probably there is a good reason why pynetbox converts the URLs apart from the general recommendation not to use underscores, although that does not seem to be backed by any RFC as far as I know) your suggestion would probably be the best possible solution. 

If any unsolvable issues should arise for anyone (I don't really expect it in this early stage of the project) the workaround sketched above or an equivalent solution for nginx would also work with reversed expressions in the `ProxyPassMatch` term, so there shouldn't be too much damage done by changing `base_url`.
